/*
 * TestApi
 * No description
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.utility.comparator.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * FileData
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2017-01-02T12:52:43.892Z")
public class FileData   {
  @JsonProperty("FileOneData")
  private String fileOneData = null;

  @JsonProperty("FileTwoData")
  private String fileTwoData = null;

  public FileData fileOneData(String fileOneData) {
    this.fileOneData = fileOneData;
    return this;
  }

   /**
   * First File Data
   * @return fileOneData
  **/
  @ApiModelProperty(required = true, value = "First File Data")
  public String getFileOneData() {
    return fileOneData;
  }

  public void setFileOneData(String fileOneData) {
    this.fileOneData = fileOneData;
  }

  public FileData fileTwoData(String fileTwoData) {
    this.fileTwoData = fileTwoData;
    return this;
  }

   /**
   * Second File Data
   * @return fileTwoData
  **/
  @ApiModelProperty(required = true, value = "Second File Data")
  public String getFileTwoData() {
    return fileTwoData;
  }

  public void setFileTwoData(String fileTwoData) {
    this.fileTwoData = fileTwoData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileData fileData = (FileData) o;
    return Objects.equals(this.fileOneData, fileData.fileOneData) &&
        Objects.equals(this.fileTwoData, fileData.fileTwoData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileOneData, fileTwoData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileData {\n");
    
    sb.append("    fileOneData: ").append(toIndentedString(fileOneData)).append("\n");
    sb.append("    fileTwoData: ").append(toIndentedString(fileTwoData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

